# Generated by Django 5.0.6 on 2024-08-13 14:03

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name for this pricing feature.', max_length=100, verbose_name='Feature Name')),
                ('description', models.TextField(blank=True, help_text='Provide a description for this pricing feature.', null=True, verbose_name='Feature Description')),
            ],
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='Enter a name for this pricing tier.', max_length=50, verbose_name='Tier Name')),
                ('price', models.PositiveSmallIntegerField(help_text='Enter the price for this tier', verbose_name='Price')),
                ('is_special', models.BooleanField(default=False, help_text='Check this box if this tier is special or recommended.', verbose_name=' Special Tier')),
                ('special_name', models.CharField(default='Recommended', help_text='Enter a name for the special tier, e.g., "Recommended"', max_length=100, verbose_name='Special Tier Name')),
                ('cta_text', models.CharField(default='Buy Now', help_text='Enter the text for the Call-to-Action (CTA) button.', max_length=100, verbose_name=' CTA Text')),
                ('cta_link', models.ForeignKey(blank=True, help_text='Choose a page to link to when the CTA button is clicked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='CTA Link')),
                ('page', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_tiers', to='wagtailcore.page')),
                ('pricing_features', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Select features associated with this pricing tier.', related_name='+', to='pricing.pricingfeature', verbose_name='Pricing Features')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
