# Generated by Django 5.0.6 on 2024-08-13 14:03

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0093_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='Enter a name for the feature.', max_length=50, verbose_name='Feature Name')),
                ('icon', models.CharField(blank=True, help_text="Enter the icon code for this feature. We are using Remix Icons (ri) URL: https://remixicon.com/, and you can find a list of icons on their website. Use icons such as 'ri-store-line'. Leave it blank if no icon is needed.", max_length=30, null=True)),
                ('color', models.CharField(blank=True, help_text=" Enter a color code for this feature, such as a hex value (e.g., ',  #e80368') or a color name (e.g., 'red'). Leave it blank if no specific color is needed.", max_length=20, null=True)),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeServiceRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_home_relation', to='features.feature')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_feature_relation', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
